development:
  environment: "homologation"
  merchant_id: "{84BE7E7F-698A-6C74-F820-AE359C2A07C2}"
  crypto_url: "http://localhost:9292"
  crypto_key: "1234561246"

test:
  environment: "homologation"
  merchant_id: "{84BE7E7F-698A-6C74-F820-AE359C2A07C2}"
  crypto_url: "http://localhost:9292"
  crypto_key: "1234561246"

production:
  environment: "production"
  merchant_id: "{84BE7E7F-698A-6C74-F820-AE359C2A07C2}"
  crypto_url: "http://localhost:9292"
  crypto_key: "1234561246"
